/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "RNMinesweeperSpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeMinesweeperCxxSpecJSI_getMinesVm(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeMinesweeperCxxSpecJSI *>(&turboModule)->getMinesVm(
    rt
  );
}
static jsi::Value __hostFunction_NativeMinesweeperCxxSpecJSI_initCells(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  static_cast<NativeMinesweeperCxxSpecJSI *>(&turboModule)->initCells(
    rt
  );
  return jsi::Value::undefined();
}
static jsi::Value __hostFunction_NativeMinesweeperCxxSpecJSI_regen(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  static_cast<NativeMinesweeperCxxSpecJSI *>(&turboModule)->regen(
    rt
  );
  return jsi::Value::undefined();
}
static jsi::Value __hostFunction_NativeMinesweeperCxxSpecJSI_open(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  static_cast<NativeMinesweeperCxxSpecJSI *>(&turboModule)->open(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber()
  );
  return jsi::Value::undefined();
}

NativeMinesweeperCxxSpecJSI::NativeMinesweeperCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("Minesweeper", jsInvoker) {
  methodMap_["getMinesVm"] = MethodMetadata {0, __hostFunction_NativeMinesweeperCxxSpecJSI_getMinesVm};
  methodMap_["initCells"] = MethodMetadata {0, __hostFunction_NativeMinesweeperCxxSpecJSI_initCells};
  methodMap_["regen"] = MethodMetadata {0, __hostFunction_NativeMinesweeperCxxSpecJSI_regen};
  methodMap_["open"] = MethodMetadata {1, __hostFunction_NativeMinesweeperCxxSpecJSI_open};
}


} // namespace facebook::react
